Including code review tools for CI
kubenow/image pull request #11
Opened 2017-05-30 08:19 UTC by carmat88

## Change content and motivation
Including and improving CI with some code review tools such as:

- `shellcheck`
- `jq`

and command feature such as `terraform fmt`

## GitHub cross-links 

**Fixes:** 

**Docs**:

2017-05-31 12:53 UTC, carmat88 commented
@mcapuccini Code review tools have been added to the CI for the image building. Please let me know if you have any comments. Cheers.

2017-06-01 11:52 UTC, mcapuccini requested changes
there is a problem with the json formatting, the rest looks good!

2017-06-01 11:52 UTC, mcapuccini commented on .travis.yml
> +  - python -mjson.tool < build-"$HOST_CLOUD".json
This always return 0. You need to do the trick with `git diff --exit-code` like above:

*untested*
```
echo "$(python -mjson.tool < build-aws.json)" > build-aws.json 
git diff --exit-code
```

2017-06-01 11:52 UTC, mcapuccini commented on .travis.yml
> +  - shellcheck -x $(find . -type f -name "*.sh")
you can remove `-x`

2017-06-01 13:10 UTC, carmat88 commented on .travis.yml
> +  - python -mjson.tool < build-"$HOST_CLOUD".json
Cool, many thanks. I just tested them locally. First time returned 1, then (after the commit of course) returned 0. Will push now changes.

2017-06-01 13:10 UTC, carmat88 commented on .travis.yml
> +  - shellcheck -x $(find . -type f -name "*.sh")
Ok, done. Will push soon change.

2017-06-01 13:57 UTC, mcapuccini approved these changes

2017-06-01 13:57 UTC, merged