Adding Packer Openstack template
kubenow/image pull request #13
Opened 2017-06-07 14:03 UTC by carmat88

## Change content and motivation

Adding a dedicated Openstack packer template as importing image created in GCE seems to not be compatible and produces error when spawning an instance based on such image.

## GitHub cross-links 

**Fixes:** 

**Docs**:

2017-06-12 08:24 UTC, mcapuccini commented
@carmat88 thanks! I am going to review soon, in the meanwhile could you merge the master in this branch? It seems out of synch with the master, even if there are no conflicts it's a bit easier to review once it's in synch.

2017-06-14 09:25 UTC, mcapuccini requested changes
Thanks @carmat88 for clean work. There are only a couple of minor things, and a potential issue with variable exports that I commented inline. In addition, I have other 2 requests/comments:

- Could you put a space after each comment hashtag `#comment` -> `# comment`. This is just to have the same style in the project. Not super important, I know 🙂 .
- Cloud you make a pre-release on this branch to check if the logic with the exported variables works?

Good job! Looking forward to the second round of review.

2017-06-14 09:25 UTC, mcapuccini commented on bin/get_current_version.sh
>  export CURRENT_VERSION
I don't think that export has any effect here. You need to export it at the end since you reassign this variable.

2017-06-14 09:25 UTC, mcapuccini commented on bin/get_current_version.sh
> +KUBENOW_REGEX='^v[0-9]{3}([ab][0-9]{1,}|rc[0-9]{1,})?$'
please change with `export KUBENOW_REGEX='^v[0-9]{3}([ab][0-9]{1,}|rc[0-9]{1,})?$'`

2017-06-14 09:25 UTC, mcapuccini commented on bin/os_main.tf
> +
maybe it looks better removing this space

2017-06-14 09:25 UTC, mcapuccini commented on bin/os_pp.sh
> +	echo "Kubenow current version tagged as release"
please indent this line

2017-06-14 13:04 UTC, carmat88 commented on bin/get_current_version.sh
>  export CURRENT_VERSION
Sure thing, forgot about it. Correcting it.

2017-06-14 13:04 UTC, carmat88 commented on bin/get_current_version.sh
> +KUBENOW_REGEX='^v[0-9]{3}([ab][0-9]{1,}|rc[0-9]{1,})?$'
As per our discussion, based on shellcheck output, it's recommended to split exporting and initialization in the same line.

2017-06-14 13:05 UTC, carmat88 commented on bin/os_main.tf
> +
Indeed, might have accidentally pressed enter there! No idea otherwise. Correcting it.

2017-06-14 13:06 UTC, carmat88 commented on bin/os_pp.sh
> +	echo "Kubenow current version tagged as release"
I think is already indented if I am not wrong. Isn't it?

2017-06-14 13:25 UTC, carmat88 commented on bin/os_main.tf
> +
So, apparently the command `terraform fmt` is adding that space. If I remove it, then the git diff test in travis after the before mentioned command will fail.

2017-06-14 13:42 UTC, mcapuccini commented on bin/os_main.tf
> +
alright! 🙂

2017-06-14 13:42 UTC, mcapuccini commented on bin/get_current_version.sh
> +KUBENOW_REGEX='^v[0-9]{3}([ab][0-9]{1,}|rc[0-9]{1,})?$'
👍

2017-06-16 09:29 UTC, carmat88 commented
@mcapuccini All changes have been applied and tested. Pre-release image 0.3.1a1 has been created and successful tested across all cloud providers. Should you have any further points, please let me know. Thank you!

2017-06-16 09:43 UTC, mcapuccini requested changes
There are a couple of things with the exports still to be solved, and a very minor indentation problem. Looks brilliant otherwise!

2017-06-16 09:43 UTC, mcapuccini commented on bin/get_current_version.sh
>  export CURRENT_VERSION
please remove this export, it has no effect here

2017-06-16 09:43 UTC, mcapuccini commented on bin/get_current_version.sh
> +export KUBENOW_REGEX
export before assign has no effect, you need to have it after assign. Also do you need to export this variable? Is it used later on?

2017-06-16 09:43 UTC, mcapuccini commented on bin/get_current_version.sh
> +# Checking whether or not current version is tagged as release
could you indent this block evenly? line 17 is not even with 13 and 15.

2017-06-16 13:11 UTC, carmat88 commented on bin/get_current_version.sh
> +export KUBENOW_REGEX
Actually no. I though I could have re-used it, but was not the case then. Removing the extras `export` lines.

2017-06-16 13:15 UTC, carmat88 commented on bin/get_current_version.sh
> +# Checking whether or not current version is tagged as release
That's weird...in my code editor is indent. I'm re-aligning and pushing the commit.

2017-06-19 08:06 UTC, mcapuccini approved these changes

2017-06-19 08:06 UTC, merged

2017-06-19 08:07 UTC, mcapuccini commented
@carmat88 thanks for nice work. It's now live. Please make release 0.3.1 at your earliest convenience.